/** SVG 입지 인포그래픽 — 원본 지도(629×374) 좌표 기준 핫스팟 */

export const MAP_BASE = {
  src: "/images/site-location-map-base.png",
  width: 629,
  height: 374,
} as const;

export type InfographicHotspot = {
  id: string;
  name: string;
  detail?: string;
  households?: number;
  /** viewBox 좌표 (원본 지도 픽셀과 1:1) */
  x: number;
  y: number;
  w: number;
  h: number;
  kind: "residential" | "school" | "park" | "transit" | "site" | "zone";
};

export const INFOGRAPHIC_META = {
  title: "송도 아이비 학원가",
  titleAccent: "랜드마크 상업시설",
  subtitle:
    "고소득층 초밀집 수요와 메인학원가로 이어지는 중심자리, 독보적인 외관특화 디자인으로 차별화된 랜드마크 상업시설",
  badgeLine1: "송도의 ‘대치동’",
  badgeLine2: "1공구 중심 상권",
  badgeEn: "THE CENTER OF EDUCATION",
} as const;

export const INFOGRAPHIC_HIGHLIGHTS = [
  {
    id: "academy",
    title: "송도 최고수준 학원가",
    body: "교육 시설 밀집과 학생 중심 소비수요가 풍부한 아이비 학원가",
  },
  {
    id: "demand",
    title: "고소득 배후수요 기반 소비 상권",
    body: "인근 고소득 대단지 거주민의 높은 소득·소비력이 상권을 지탱",
  },
  {
    id: "park",
    title: "센트럴파크 연계 여가·문화 상권",
    body: "센트럴파크·아트센터 등 외부 방문객 유입으로 체류·여가 수요 확보",
  },
] as const;

/**
 * 원본 인포그래픽 라벨 기준 단지·시설 핫스팟
 * 좌표는 site-location-map-base.png (629×374) 기준
 */
export const INFOGRAPHIC_HOTSPOTS: InfographicHotspot[] = [
  {
    id: "zone-academy",
    name: "송도 아이비 학원가",
    detail: "주거밀착 · 학원 · 이면 상권",
    x: 300,
    y: 130,
    w: 120,
    h: 90,
    kind: "zone",
  },

  // —— 스쿨존 (상단 중앙) ——
  {
    id: "school-zone",
    name: "수도권 최고의 스쿨존",
    detail: "신정중 · 연송고 · 명선초 · 포스코고",
    x: 250,
    y: 18,
    w: 118,
    h: 72,
    kind: "school",
  },
  {
    id: "s-chadwick",
    name: "채드윅송도국제학교",
    x: 268,
    y: 95,
    w: 72,
    h: 48,
    kind: "school",
  },
  {
    id: "s-sinjeong",
    name: "신정중학교",
    x: 255,
    y: 28,
    w: 48,
    h: 18,
    kind: "school",
  },
  {
    id: "s-yeonsong",
    name: "연송고등학교",
    x: 255,
    y: 44,
    w: 52,
    h: 16,
    kind: "school",
  },
  {
    id: "s-myeong",
    name: "명선초등학교",
    x: 255,
    y: 58,
    w: 52,
    h: 16,
    kind: "school",
  },
  {
    id: "s-posco",
    name: "포스코고등학교",
    x: 255,
    y: 72,
    w: 52,
    h: 16,
    kind: "school",
  },

  // —— 북서 · 커낼/더카운티/그린워크 ——
  {
    id: "r-county-d4",
    name: "송도더카운티 II",
    detail: "D4",
    households: 204,
    x: 118,
    y: 88,
    w: 70,
    h: 28,
    kind: "residential",
  },
  {
    id: "r-county-d5",
    name: "송도더카운티 III",
    detail: "D5",
    households: 134,
    x: 118,
    y: 118,
    w: 70,
    h: 28,
    kind: "residential",
  },
  {
    id: "r-county-d2",
    name: "송도더카운티 I",
    detail: "D2",
    households: 133,
    x: 118,
    y: 148,
    w: 70,
    h: 28,
    kind: "residential",
  },
  {
    id: "r-greenwalk-2",
    name: "송도더샵그린워크",
    detail: "2차",
    households: 665,
    x: 38,
    y: 72,
    w: 78,
    h: 28,
    kind: "residential",
  },
  {
    id: "r-greenwalk-1a",
    name: "송도더샵그린워크",
    detail: "1차 27BL",
    households: 358,
    x: 38,
    y: 104,
    w: 78,
    h: 28,
    kind: "residential",
  },
  {
    id: "r-greenwalk-1b",
    name: "송도더샵그린워크",
    detail: "1차",
    households: 654,
    x: 38,
    y: 136,
    w: 78,
    h: 28,
    kind: "residential",
  },
  {
    id: "r-greenwalk-3a",
    name: "송도더샵그린워크",
    detail: "3차 D18",
    households: 785,
    x: 38,
    y: 40,
    w: 78,
    h: 28,
    kind: "residential",
  },
  {
    id: "r-greenwalk-3b",
    name: "송도더샵그린워크",
    detail: "3차 D17",
    households: 380,
    x: 38,
    y: 10,
    w: 78,
    h: 28,
    kind: "residential",
  },

  // —— 서·남 · 퍼스트파크 / 마스터뷰 / 센트럴파크 ——
  {
    id: "r-first-15",
    name: "송도더샵퍼스트파크",
    detail: "15블럭",
    households: 872,
    x: 155,
    y: 195,
    w: 92,
    h: 26,
    kind: "residential",
  },
  {
    id: "r-first-14",
    name: "송도더샵퍼스트파크",
    detail: "14블럭",
    households: 869,
    x: 155,
    y: 224,
    w: 92,
    h: 26,
    kind: "residential",
  },
  {
    id: "r-first-13",
    name: "송도더샵퍼스트파크",
    detail: "13블럭",
    households: 856,
    x: 155,
    y: 252,
    w: 92,
    h: 26,
    kind: "residential",
  },
  {
    id: "r-master-21",
    name: "송도더샵마스터뷰",
    detail: "21블록",
    households: 698,
    x: 95,
    y: 210,
    w: 58,
    h: 36,
    kind: "residential",
  },
  {
    id: "r-master-22",
    name: "송도더샵마스터뷰",
    detail: "22블록",
    households: 691,
    x: 95,
    y: 250,
    w: 58,
    h: 36,
    kind: "residential",
  },
  {
    id: "r-master-23",
    name: "송도더샵마스터뷰",
    detail: "23-1블록",
    households: 548,
    x: 95,
    y: 290,
    w: 58,
    h: 36,
    kind: "residential",
  },
  {
    id: "r-artwin",
    name: "송도아트윈푸르지오",
    households: 999,
    x: 52,
    y: 268,
    w: 40,
    h: 40,
    kind: "residential",
  },
  {
    id: "r-cp-prugio",
    name: "송도센트럴파크푸르지오",
    households: 551,
    x: 250,
    y: 300,
    w: 78,
    h: 28,
    kind: "residential",
  },
  {
    id: "r-cp-prugio-city",
    name: "송도센트럴파크푸르지오시티",
    households: 1140,
    x: 250,
    y: 332,
    w: 90,
    h: 28,
    kind: "residential",
  },

  // —— 중앙 · 그린에비뉴 / 하버뷰 ——
  {
    id: "r-greenave-8",
    name: "송도더샵그린에비뉴",
    detail: "8단지",
    households: 474,
    x: 340,
    y: 55,
    w: 78,
    h: 28,
    kind: "residential",
  },
  {
    id: "r-greenave-7",
    name: "송도더샵그린에비뉴",
    detail: "7단지",
    households: 540,
    x: 340,
    y: 88,
    w: 78,
    h: 28,
    kind: "residential",
  },
  {
    id: "r-harbor-14",
    name: "송도더샵하버뷰",
    detail: "14단지",
    households: 506,
    x: 220,
    y: 155,
    w: 70,
    h: 26,
    kind: "residential",
  },
  {
    id: "r-harbor-13",
    name: "송도더샵하버뷰",
    detail: "13단지",
    households: 553,
    x: 220,
    y: 182,
    w: 70,
    h: 26,
    kind: "residential",
  },
  {
    id: "r-prugio-harbor",
    name: "송도푸르지오하버뷰",
    households: 593,
    x: 195,
    y: 290,
    w: 52,
    h: 32,
    kind: "residential",
  },
  {
    id: "r-xi-1",
    name: "송도자이하버뷰",
    detail: "1단지",
    households: 546,
    x: 175,
    y: 325,
    w: 58,
    h: 26,
    kind: "residential",
  },
  {
    id: "r-xi-2",
    name: "송도자이하버뷰",
    detail: "2단지",
    households: 523,
    x: 175,
    y: 350,
    w: 58,
    h: 22,
    kind: "residential",
  },

  // —— 동 · 월드마크 / 힐스테이트 / 풍림 ——
  {
    id: "r-worldmark-1",
    name: "푸르지오월드마크",
    detail: "1단지",
    households: 100,
    x: 400,
    y: 175,
    w: 58,
    h: 24,
    kind: "residential",
  },
  {
    id: "r-worldmark-2",
    name: "푸르지오월드마크",
    detail: "2단지",
    households: 97,
    x: 400,
    y: 200,
    w: 58,
    h: 24,
    kind: "residential",
  },
  {
    id: "r-worldmark-7",
    name: "푸르지오월드마크",
    detail: "7단지",
    households: 96,
    x: 385,
    y: 230,
    w: 58,
    h: 24,
    kind: "residential",
  },
  {
    id: "r-worldmark-8",
    name: "푸르지오월드마크",
    detail: "8단지",
    households: 116,
    x: 385,
    y: 255,
    w: 58,
    h: 24,
    kind: "residential",
  },
  {
    id: "r-hill-3",
    name: "송도힐스테이트",
    detail: "3단지",
    households: 108,
    x: 455,
    y: 200,
    w: 52,
    h: 22,
    kind: "residential",
  },
  {
    id: "r-hill-4",
    name: "송도힐스테이트",
    detail: "4단지",
    households: 108,
    x: 455,
    y: 224,
    w: 52,
    h: 22,
    kind: "residential",
  },
  {
    id: "r-hill-5",
    name: "송도힐스테이트",
    detail: "5단지",
    households: 118,
    x: 455,
    y: 248,
    w: 52,
    h: 22,
    kind: "residential",
  },
  {
    id: "r-hill-6",
    name: "송도힐스테이트",
    detail: "6단지",
    households: 231,
    x: 455,
    y: 272,
    w: 52,
    h: 22,
    kind: "residential",
  },
  {
    id: "r-poong-1",
    name: "송도풍림아이원",
    detail: "1단지",
    households: 1024,
    x: 530,
    y: 175,
    w: 72,
    h: 28,
    kind: "residential",
  },
  {
    id: "r-poong-2",
    name: "송도풍림아이원",
    detail: "2단지",
    households: 958,
    x: 530,
    y: 208,
    w: 72,
    h: 28,
    kind: "residential",
  },
  {
    id: "r-poong-3",
    name: "송도풍림아이원",
    detail: "3단지",
    households: 504,
    x: 530,
    y: 240,
    w: 72,
    h: 28,
    kind: "residential",
  },
  {
    id: "r-poong-4",
    name: "송도풍림아이원",
    detail: "4단지",
    households: 504,
    x: 530,
    y: 272,
    w: 72,
    h: 28,
    kind: "residential",
  },
  {
    id: "r-poong-6",
    name: "송도풍림아이원",
    detail: "6단지",
    households: 344,
    x: 530,
    y: 304,
    w: 72,
    h: 28,
    kind: "residential",
  },
  {
    id: "r-cp2",
    name: "송도더샵센트럴파크",
    detail: "2차",
    households: 632,
    x: 480,
    y: 95,
    w: 78,
    h: 28,
    kind: "residential",
  },
  {
    id: "r-cp1",
    name: "송도더샵센트럴파크",
    detail: "1차",
    households: 729,
    x: 480,
    y: 128,
    w: 78,
    h: 28,
    kind: "residential",
  },

  // —— 공원·교통 ——
  {
    id: "park-central",
    name: "송도센트럴파크",
    detail: "여가·문화",
    x: 20,
    y: 300,
    w: 120,
    h: 60,
    kind: "park",
  },
  {
    id: "t-ibd",
    name: "국제업무지구역",
    detail: "인천1호선",
    x: 8,
    y: 175,
    w: 70,
    h: 22,
    kind: "transit",
  },
  {
    id: "t-cp",
    name: "센트럴파크역",
    detail: "인천1호선",
    x: 55,
    y: 330,
    w: 62,
    h: 22,
    kind: "transit",
  },

  // 사업지는 맨 아래 선언 → 클릭 우선
  {
    id: "site",
    name: "송도 하늘채 아이비원",
    detail: "단지 내 상가",
    x: 318,
    y: 148,
    w: 52,
    h: 36,
    kind: "site",
  },
];
